# Generated by Django 2.0.6 on 2018-07-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagitem',
            options={'verbose_name': 'Тегер', 'verbose_name_plural': 'Тегеры'},
        ),
    ]
