# Generated by Django 2.0.6 on 2018-07-02 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='имя')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('precondition', models.CharField(max_length=1000, verbose_name='предварительное условие')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('change', models.DateTimeField(auto_now=True, verbose_name='последнее изменение')),
                ('status', models.CharField(choices=[('No_test', 'Не тесировался'), ('Fail', 'Провал'), ('Done', 'Прошел'), ('Error', 'Ошибка')], default='Не тесировался', max_length=15)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tag.Tag', verbose_name='тег')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
            ],
            options={
                'verbose_name': 'Тест План',
                'verbose_name_plural': 'Тест План',
            },
        ),
        migrations.AddField(
            model_name='logplan',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testplan.TestPlan'),
        ),
        migrations.AddField(
            model_name='logplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
    ]
