# Generated by Django 2.0.6 on 2018-07-03 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0003_auto_20180703_0601'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.TestCase')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testplan.TestPlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='testplan',
            name='test_case',
            field=models.ManyToManyField(through='testplan.PlanCase', to='testcase.TestCase'),
        ),
    ]
