# Generated by Django 2.0.6 on 2018-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0002_auto_20180703_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logplan',
            options={'verbose_name': 'Лог плана', 'verbose_name_plural': 'Логи планов'},
        ),
        migrations.AlterModelOptions(
            name='plancase',
            options={'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
        migrations.AlterField(
            model_name='testplan',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Описание тест плана'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название тест плана'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('No_test', 'Не тесировался'), ('Fail', 'Провал'), ('Done', 'Прошел'), ('Error', 'Ошибка')], default='No_test', max_length=15, verbose_name='статус'),
        ),
    ]
